### ISSUE TITLE
doesn´t work on gnome 43 archlinux

### ISSUE THREAD

**Issue by Neo-29** [MacTavishAO/nautilus-admin-gtk4#1]
Nothing in the menu to open as admin

**Comment by MacTavishAO** [comment]
Can you confirm python-nautilus and polkit are installed?

It'd be very helpful if you could paste output of the command below here because it's working on my arch system.

`nautilus -q ; nautilus`

**Comment by MacTavishAO** [comment]
Arch still ships an older version of python-nautilus. Please upgrade to 4.0 using fcgu repos or install the package directly.

FCGU repos: https://gitlab.com/fabiscafe/gnome-unstable
Direct link to package itself: https://br-mirror.amanoteam.com/fcgu/python-nautilus-4.0-0.1-x86_64.pkg.tar.zst

Use `pacman -U python-nautilus-4.0-0.1-x86_64.pkg.tar.zst` to install the package or follow the steps on FCGU repos.

**Comment by MacTavishAO** [comment]
I updated AUR package to depend on [python-nautilus-gtk4](https://aur.archlinux.org/packages/python-nautilus-gtk4). Please update nautilus-admin-gtk4 to latest version. Your AUR helper should fix this issue for you.

**Comment by Neo-29** [comment]
Update of `python-nautlius-gtk4` arrived today.
All working now.
I close
